version: "3"

tasks:
  build:
    cmds:
      - wails3 task build:frontend
      - go build -ldflags="-H windowsgui -s -w" -o build/bin/sni-gui.exe .
    sources:
      - "**/*.go"
      - "frontend/dist/**/*"
    generates:
      - "build/bin/sni-gui.exe"

  build:frontend:
    dir: frontend
    cmds:
      - npm run build
    sources:
      - "src/**/*"
      - "package.json"
    generates:
      - "dist/**/*"

  dev:
    cmds:
      - wails3 dev

  generate:
    cmds:
      - wails3 generate bindings -ts

  doctor:
    cmds:
      - wails3 doctor