// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EngineService is the Wails v3 service exposed to the React frontend.
 * Every method is a thin pass-through to the Rust cdylib (see rust_engine.go).
 * Return values are JSON strings so the frontend parses once and stays
 * in sync with the Rust Snapshot / probe schemas.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CancelProbe cooperatively cancels a running probe (B4).
 */
export function CancelProbe(): $CancellablePromise<void> {
    return $Call.ByID(3167743581);
}

export function ClearLogs(): $CancellablePromise<string> {
    return $Call.ByID(3620219459);
}

/**
 * ConfigLoad reads the config JSON from disk.
 */
export function ConfigLoad(): $CancellablePromise<string> {
    return $Call.ByID(1161191425);
}

/**
 * ConfigPath returns the path of config.json.
 */
export function ConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(2989077374);
}

/**
 * ConfigSave writes the config JSON to disk atomically.
 * FIX(config-race): serialized under configWriteMu (then s.mu) so a
 * frontend auto-save racing the tray toggle queues instead of
 * interleaving writes and losing changes.
 */
export function ConfigSave(configJSON: string): $CancellablePromise<string> {
    return $Call.ByID(107538784, configJSON);
}

/**
 * EmitLogs pushes new log lines to the frontend.
 */
export function EmitLogs(): $CancellablePromise<void> {
    return $Call.ByID(395237335);
}

/**
 * EmitProbeResults pushes probe results to the frontend.
 */
export function EmitProbeResults(): $CancellablePromise<void> {
    return $Call.ByID(3444502444);
}

/**
 * EmitStats is called periodically by the frontend to poll stats.
 * The frontend can also listen to a "stats" event if we push from Go.
 */
export function EmitStats(): $CancellablePromise<void> {
    return $Call.ByID(602070487);
}

export function ExportLogs(): $CancellablePromise<string> {
    return $Call.ByID(2091104638);
}

/**
 * FIX(config-race): the frontend can poll this to make sure a
 * save finished before the window closes.
 */
export function FlushConfig(): $CancellablePromise<void> {
    return $Call.ByID(2231200897);
}

/**
 * GetActiveConnections returns live relay sessions as a JSON array (U5).
 */
export function GetActiveConnections(): $CancellablePromise<string> {
    return $Call.ByID(3232225112);
}

/**
 * GetDefaultConfig returns the seeded first-launch defaults (WP0.2).
 */
export function GetDefaultConfig(): $CancellablePromise<string> {
    return $Call.ByID(4248131124);
}

export function GetLogs(): $CancellablePromise<string> {
    return $Call.ByID(770568146);
}

export function GetProbeResults(): $CancellablePromise<string> {
    return $Call.ByID(1987239213);
}

export function GetSniResults(): $CancellablePromise<string> {
    return $Call.ByID(787998947);
}

export function GetStats(): $CancellablePromise<string> {
    return $Call.ByID(3735442344);
}

export function IsAdmin(): $CancellablePromise<boolean> {
    return $Call.ByID(1453540066);
}

/**
 * FIX(A3): backend liveness probe for the UI resync tick.
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(2596871714);
}

/**
 * FIX(ui): zero the stats counters (Active, Total, OK, Fail,
 * Up, Down, boards) without touching the running engine.
 */
export function ResetStats(): $CancellablePromise<string> {
    return $Call.ByID(409054981);
}

export function RunProbeEndpoints(endpointsJSON: string): $CancellablePromise<string> {
    return $Call.ByID(3540143948, endpointsJSON);
}

export function RunProbeSnis(snisJSON: string, endpoint: string): $CancellablePromise<string> {
    return $Call.ByID(1202344827, snisJSON, endpoint);
}

export function SelfTest(configPath: string): $CancellablePromise<string> {
    return $Call.ByID(2187411257, configPath);
}

/**
 * FIX(tray-rewrite): SetTrayEnabled — single writer for TRAY_ENABLED.
 * Serialized under s.mu against ConfigSave/Start/Stop; persists via Rust
 * then applies via TrayManager.Ensure. Strips the inert "ok" key from the
 * load payload before re-saving so it never pollutes config.json.
 * FIX(config-race): also serialized under configWriteMu (acquired before
 * s.mu) so a tray write racing a frontend auto-save cannot interleave.
 */
export function SetTrayEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2988867814, enabled);
}

/**
 * FIX(perf): single-call snapshot for the 1Hz poller.
 */
export function SnapshotAll(logSince: number): $CancellablePromise<string> {
    return $Call.ByID(2257748210, logSince);
}

/**
 * StartEngine is callable from the frontend as StartEngine(configJSON).
 */
export function StartEngine(configJSON: string): $CancellablePromise<string> {
    return $Call.ByID(1832008731, configJSON);
}

/**
 * FIX #9: tray-initiated engine start using the saved config.
 */
export function StartFromTray(): $CancellablePromise<void> {
    return $Call.ByID(874873277);
}

export function StopEngine(): $CancellablePromise<string> {
    return $Call.ByID(2951693865);
}

/**
 * FIX #9: tray-initiated engine stop.
 */
export function StopFromTray(): $CancellablePromise<void> {
    return $Call.ByID(2242411847);
}

/**
 * TrayPersistedEnabled reads the on-disk TRAY_ENABLED value (tolerant
 * coercion, defaults true). Used by Reload/Reset to re-apply only when
 * disk and runtime disagree.
 */
export function TrayPersistedEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(3483782881);
}

/**
 * FIX(dedup): TrayIsEnabled (legacy duplicate of the probe below)
 * was removed; this is the single runtime probe. TrayPersistedEnabled
 * reads the on-disk value instead.
 */
export function TrayRuntimeActive(): $CancellablePromise<boolean> {
    return $Call.ByID(1904414495);
}

/**
 * FIX(titlebar): window controls with explicit error returns so
 * the frontend cannot silently swallow failures.
 * FIX(config-persist): the frontend flushes config on
 * beforeunload / visibilitychange before this runs.
 * FIX(quit): the close-vs-quit decision is made in main.go's
 * WindowClosing hook using the package-level `quitting` flag.
 * This wrapper stays a thin forwarder.
 */
export function WindowClose(): $CancellablePromise<void> {
    return $Call.ByID(3990933141);
}

/**
 * FIX(dedup): canonical maximise-state probe. The old IsMaximised
 * wrapper was removed; this is the single source of truth.
 */
export function WindowIsMaximised(): $CancellablePromise<boolean> {
    return $Call.ByID(802863560);
}

/**
 * FIX(titlebar): window controls with explicit error returns so
 * the frontend cannot silently swallow failures.
 */
export function WindowMinimise(): $CancellablePromise<void> {
    return $Call.ByID(786743050);
}

/**
 * FIX(#1): manual window drag for the frameless title bar. The Window
 * interface exposes no exported drag method in beta.20 (startDrag is
 * unexported), so this routes through the exported HandleMessage path
 * ("wails:drag"), which the WebviewWindow handles natively.
 * TODO(#1): if a future Wails beta exports a drag method, prefer it here.
 */
export function WindowStartDrag(): $CancellablePromise<void> {
    return $Call.ByID(2241193379);
}

/**
 * FIX(titlebar): window controls with explicit error returns so
 * the frontend cannot silently swallow failures.
 */
export function WindowToggleMaximise(): $CancellablePromise<void> {
    return $Call.ByID(2103993100);
}
