// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EngineService is the Wails v3 service exposed to the React frontend.
 * Every method is a thin pass-through to the Rust cdylib (see rust_engine.go).
 * Return values are JSON strings so the frontend parses once and stays
 * in sync with the Rust Snapshot / probe schemas.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CancelProbe cooperatively cancels a running probe (B4).
 */
export function CancelProbe(): $CancellablePromise<void> {
    return $Call.ByID(3167743581);
}

export function ClearLogs(): $CancellablePromise<string> {
    return $Call.ByID(3620219459);
}

/**
 * ConfigLoad reads the config JSON from disk.
 */
export function ConfigLoad(): $CancellablePromise<string> {
    return $Call.ByID(1161191425);
}

/**
 * ConfigPath returns the path of config.json.
 */
export function ConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(2989077374);
}

/**
 * ConfigSave writes the config JSON to disk atomically.
 */
export function ConfigSave(configJSON: string): $CancellablePromise<string> {
    return $Call.ByID(107538784, configJSON);
}

/**
 * EmitLogs pushes new log lines to the frontend.
 */
export function EmitLogs(): $CancellablePromise<void> {
    return $Call.ByID(395237335);
}

/**
 * EmitProbeResults pushes probe results to the frontend.
 */
export function EmitProbeResults(): $CancellablePromise<void> {
    return $Call.ByID(3444502444);
}

/**
 * EmitStats is called periodically by the frontend to poll stats.
 * The frontend can also listen to a "stats" event if we push from Go.
 */
export function EmitStats(): $CancellablePromise<void> {
    return $Call.ByID(602070487);
}

export function ExportLogs(): $CancellablePromise<string> {
    return $Call.ByID(2091104638);
}

/**
 * GetActiveConnections returns live relay sessions as a JSON array (U5).
 */
export function GetActiveConnections(): $CancellablePromise<string> {
    return $Call.ByID(3232225112);
}

/**
 * GetDefaultConfig returns the seeded first-launch defaults (WP0.2).
 */
export function GetDefaultConfig(): $CancellablePromise<string> {
    return $Call.ByID(4248131124);
}

export function GetLogs(): $CancellablePromise<string> {
    return $Call.ByID(770568146);
}

export function GetProbeResults(): $CancellablePromise<string> {
    return $Call.ByID(1987239213);
}

export function GetSniResults(): $CancellablePromise<string> {
    return $Call.ByID(787998947);
}

export function GetStats(): $CancellablePromise<string> {
    return $Call.ByID(3735442344);
}

export function IsAdmin(): $CancellablePromise<boolean> {
    return $Call.ByID(1453540066);
}

/**
 * FIX(A3): backend liveness probe for the UI resync tick.
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(2596871714);
}

export function RunProbeEndpoints(endpointsJSON: string): $CancellablePromise<string> {
    return $Call.ByID(3540143948, endpointsJSON);
}

export function RunProbeSnis(snisJSON: string, endpoint: string): $CancellablePromise<string> {
    return $Call.ByID(1202344827, snisJSON, endpoint);
}

export function SelfTest(configPath: string): $CancellablePromise<string> {
    return $Call.ByID(2187411257, configPath);
}

/**
 * StartEngine is callable from the frontend as StartEngine(configJSON).
 */
export function StartEngine(configJSON: string): $CancellablePromise<string> {
    return $Call.ByID(1832008731, configJSON);
}

export function StopEngine(): $CancellablePromise<string> {
    return $Call.ByID(2951693865);
}
